import os
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "ollama").lower()

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://ollama:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1:8b")

app = FastAPI(title="Text2SQL Service")

class RequestMessage(BaseModel):
    message: str

def build_prompt(user_message: str) -> str:
    return f"""
You are a Text2SQL assistant for a PostgreSQL database (multi-entity finance).
Tu es un assistant Text2SQL pour une base PostgreSQL (finance multi-entité).

STRICT RULES / RÈGLES STRICTES:
- Output ONLY ONE PostgreSQL SQL statement.
- No explanation, no markdown, no comments.
- Never use DROP, ALTER, TRUNCATE.
- Prefer SELECT unless user explicitly asks to create/update something.

USER REQUEST / DEMANDE:
{user_message}

SQL:
""".strip()

def call_ollama(prompt: str) -> str:
    try:
        r = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            timeout=300
        )
        r.raise_for_status()
        data = r.json()
        sql = (data.get("response") or "").strip()
        sql = sql.replace("```sql", "").replace("```", "").strip()
        if not sql:
            raise HTTPException(status_code=500, detail="Empty SQL generated by Ollama")
        return sql
    except requests.RequestException as e:
        raise HTTPException(status_code=500, detail=f"Ollama request failed: {e}")

@app.post("/convert")
def convert_to_sql(req: RequestMessage):
    prompt = build_prompt(req.message)

    if LLM_PROVIDER == "ollama":
        sql = call_ollama(prompt)
        return {"sql": sql}

    # Si tu veux garder OpenAI en option, on le fera plus tard.
    raise HTTPException(status_code=500, detail=f"Unsupported LLM_PROVIDER: {LLM_PROVIDER}")
